build:
	tsc
	cp index.html dist/

pack:
	cp index.html dist/
	webpack

zip: pack
	cd dist; zip plugin.zip index.html main.js

upload:
	pluginmgr --filename dist/plugin.zip upload {{cookiecutter.plugin_name}}