build:
	tsc

pack:
	cp index.html dist/
	webpack --mode=production

dev-pack:
	cp index.html dist/
	webpack --mode=development

zip: pack
	cd dist; zip plugin.zip index.html main.js

dev-zip: dev-pack
	cd dist; zip plugin.zip index.html main.js

upload:
	pluginmgr --filename dist/plugin.zip upload {{cookiecutter.plugin_name}}